### ISSUE TITLE
Unable to push log to report portal using ReportingApi.log()

### ISSUE THREAD

**Issue by vaibhavjagdale** [reportportal/agent-js-webdriverio#25]
I am using @reportportal/agent-js-webdriverio npm module to push log statements written in test to report portal.
I used below code snippet.

```
const { Reporter } = require('@reportportal/agent-js-webdriverio');
ReportingApi.log('INFO', 'info log with attachment');
```
Logs is not able to push to report portal.
I am looking for log statement similar as provided in screenshots.
![image](https://user-images.githubusercontent.com/50039131/162407013-501ab9c5-6715-4841-89da-754f50fc848e.png)

**Comment by AmsterGet** [comment]
Hello @vaibhavjagdale !
Are you calling `ReportingApi.log` inside your tests? Did you have any errors in the console?

**Comment by vaibhavjagdale** [comment]
@AmsterGet Yes I am calling inside tests and error is ReportingApi.log is not function.

**Comment by chivekrodis** [comment]
Hello @vaibhavjagdale 
Can you please share your test?
Also we have [examples repo](https://github.com/reportportal/examples-js). There are some examples for agent-js-webdriverio with different frameworks

**Comment by AmsterGet** [comment]
> I am using @reportportal/agent-js-webdriverio npm module to push log statements written in test to report portal. I used below code snippet.
> 
> ```
> const { Reporter } = require('@reportportal/agent-js-webdriverio');
> ReportingApi.log('INFO', 'info log with attachment');
> ```
> 
> Logs is not able to push to report portal. I am looking for log statement similar as provided in screenshots. ![image](https://user-images.githubusercontent.com/50039131/162407013-501ab9c5-6715-4841-89da-754f50fc848e.png)

According to your code snippet you are imported `reporter` from `'@reportportal/agent-js-webdriverio'` instead of `ReportingApi`.
Please let us know if you have already fixed the issue.

**Comment by AmsterGet** [comment]
Hello @vaibhavjagdale !
I'll close the issue. Feel free to reopen it in case of any questions.
