### ISSUE TITLE
Allow adding browser parameters to test

### ISSUE THREAD

**Issue by hammzj** [reportportal/agent-js-webdriverio#33]
On the "Item Details" page for a test, there is a section named "Parameters" which is for the browser parameters. However, nothing ever appears there. It would be a great addition if we could manually add browser parameters to tests like we can for logs and attachments with a method like `addParameter(key, value)`.

**Comment by AmsterGet** [comment]
Browser parameter added in version [5.1.0](https://github.com/reportportal/agent-js-webdriverio/releases/tag/v5.1.0).
