### ISSUE TITLE
How to get launchId of completed launch to use in separate API call

### ISSUE THREAD

**Issue by CraigAndrew** [reportportal/agent-js-webdriverio#50]
Hi There,

Is it possible to access the launchId for a launch created via this library?

Context:
- I need to create the launch via this plugin
- Access launchId
- Query API directly inputting launchId
- Accessing launch stats to build up message to post to slack along with the launchURL as well

N.B: previous library used `wdio-reportportal-reporter` (3rd party library) allowed access to it via environment variable:
e.g: `const uuid = process.env.RP_LAUNCH_ID;`

Any help appreciated

**Comment by AmsterGet** [comment]
Hi @CraigAndrew !
We have [`launchUUIDprint`](https://github.com/reportportal/client-javascript#:~:text=eg.%20timeout.-,launchUuidPrint,-Optional) option in the RP client lib. We plan to support it in this agent as well.
Now it supports only two output targets: 'STDOUT', 'STDERR'.
Will it suites you if an additional 'environment' output target and may be 'file' will be added to it?

**Comment by CraigAndrew** [comment]
Yes that would be brilliant thanks. Right now I'm making a network call to
fetch the latest launches and using the latest one which is not robust
because it can clash with other launces that finish at the same time

**Comment by owens-ben** [comment]
Would be great if there was basically any way to get the UUID or URL of a launch after it completes, especially a merged launch

**Comment by AmsterGet** [comment]
Hi guys!
We've just released this feature in `client-javascript` version [5.1.3](https://github.com/reportportal/client-javascript/releases/tag/v5.1.3).
So you can use this feature by simply reinstalling the `agent-js-webdriverio` version.
The documentation has been updated accordingly.
